var shell = require('shelljs')
var str = shell.cat('public/index.html')
var startIndex = str.indexOf('<script src="/app.js"></script>')
str = str.slice(0, startIndex + 13) + str.slice(startIndex + 14)
str.to('public/index.html')
